import { useMemo } from 'react';
import {
  Alert,
  Box,
  Chip,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import { useApp } from '../context/AppContext';

export function NotificationsPage() {
  const { data, currentUser, isAdmin, getUserById } = useApp();

  const rows = useMemo(() => {
    const all = [...(data.notifications ?? [])].sort(
      (a, b) => b.sentAt.localeCompare(a.sentAt),
    );
    if (!currentUser) return [];
    if (isAdmin) return all;
    return all.filter(
      (n) =>
        n.toUserIds.includes(currentUser.id) ||
        n.triggeredByUserId === currentUser.id,
    );
  }, [data.notifications, currentUser, isAdmin]);

  if (!currentUser) {
    return <Typography>Select a user identity to view notifications.</Typography>;
  }

  return (
    <Box>
      <Stack mb={3}>
        <Typography variant="h4" fontWeight={700}>
          Email Notifications
        </Typography>
        <Typography color="text.secondary">
          Messages generated by workflow notification steps (stored locally —
          no external mail server in this demo).
        </Typography>
      </Stack>

      {rows.length === 0 ? (
        <Alert severity="info">
          No notifications yet. Add a <strong>Notify</strong> step in a workflow
          to send templated emails when requests reach that step.
        </Alert>
      ) : (
        <TableContainer component={Paper} elevation={1}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>Sent</TableCell>
                <TableCell>Request</TableCell>
                <TableCell>Step</TableCell>
                <TableCell>To</TableCell>
                <TableCell>Subject</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {rows.map((n) => {
                const trigger = getUserById(n.triggeredByUserId);
                return (
                  <TableRow key={n.id} hover>
                    <TableCell>
                      <Typography variant="body2">
                        {new Date(n.sentAt).toLocaleString()}
                      </Typography>
                      {trigger && (
                        <Typography variant="caption" color="text.secondary">
                          by {trigger.firstName} {trigger.lastName}
                        </Typography>
                      )}
                    </TableCell>
                    <TableCell>
                      <Typography
                        component={RouterLink}
                        to={`/register/${n.submissionId}`}
                        variant="body2"
                        fontWeight={600}
                        sx={{ color: 'primary.main', textDecoration: 'none' }}
                      >
                        {n.submissionId}
                      </Typography>
                    </TableCell>
                    <TableCell>{n.nodeLabel}</TableCell>
                    <TableCell>
                      <Stack spacing={0.5}>
                        {n.toEmails.length === 0 ? (
                          <Typography variant="body2" color="text.secondary">
                            No recipients
                          </Typography>
                        ) : (
                          n.toEmails.map((email) => (
                            <Chip key={email} size="small" label={email} />
                          ))
                        )}
                      </Stack>
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" fontWeight={600}>
                        {n.subject}
                      </Typography>
                      <Typography
                        variant="caption"
                        color="text.secondary"
                        sx={{
                          display: '-webkit-box',
                          WebkitLineClamp: 2,
                          WebkitBoxOrient: 'vertical',
                          overflow: 'hidden',
                          whiteSpace: 'pre-wrap',
                        }}
                      >
                        {n.body}
                      </Typography>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </TableContainer>
      )}
    </Box>
  );
}
